services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: Server_robopy
    ports:
      - "8081:8081"
    networks:
      - robopy_net

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: Client_robopy
    depends_on:
      - server
    environment:
      - SERVER_HOST=server
      - SERVER_PORT=8081
      - FURHAT_HOST=host.docker.internal
      - HOME=/tmp
      - XDG_CACHE_HOME=/tmp/.cache
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
    networks:
      - robopy_net
    tty: true
    privileged: true
    devices:
      - /dev/snd:/dev/snd
    volumes:
      - whisper_cache:/tmp/.cache
      - /run/user/1000/pulse:/run/user/1000/pulse:rw
      - /var/lib/dbus:/var/lib/dbus:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  robopy_net:
    name: robopy_net

volumes:
  whisper_cache:
