version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: Server_robopy
    ports:
      - "8081:8081"
    networks:
      - robopy_net

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: Client_robopy
    depends_on:
      - server
    environment:
      - SERVER_HOST=server
      - SERVER_PORT=8081
      - FURHAT_HOST=host.docker.internal
    networks:
      - robopy_net

    stdin_open: true
    tty: true

networks:
  robopy_net:
    driver: bridge
