FROM debian:bullseye

RUN apt-get update && \
    apt-get install -y build-essential libcurl4-openssl-dev libcjson-dev && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app/src
COPY server/src/ /app/src/

RUN make

RUN mv /app/src/server /app/server && chmod +x /app/server

WORKDIR /app
EXPOSE 8081

CMD ["./server"]


