FROM python:3.13.5-slim-bullseye

WORKDIR /app


RUN apt-get update && \
    apt-get install -y libportaudio2 libportaudiocpp0 ffmpeg && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY client/ /app
RUN pip install --no-cache-dir -r requirements.txt
CMD ["python", "client-python.py"]
