FROM debian:bullseye

RUN apt-get update && \
    apt-get install -y build-essential libcurl4-openssl-dev libcjson-dev && \
    apt-get clean

WORKDIR /app/src
COPY server/ /app

RUN make

EXPOSE 8081

CMD ["./server"]
